# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/DataScience_exploration',
                'doc_host': 'https://Ramon-PR.github.io',
                'git_url': 'https://github.com/Ramon-PR/DataScience_exploration',
                'lib_path': 'DataScience_exploration'},
  'syms': {'DataScience_exploration.core': {'DataScience_exploration.core.foo': ('core.html#foo', 'DataScience_exploration/core.py')}}}
